In [2]:
!pip install cirq

     |████████████████████████████████| 48 kB 4.2 MB/s 
     |████████████████████████████████| 593 kB 8.6 MB/s 
     |████████████████████████████████| 56 kB 4.6 MB/s 
     |████████████████████████████████| 1.8 MB 53.3 MB/s 
     |████████████████████████████████| 541 kB 54.2 MB/s 
     |████████████████████████████████| 52 kB 1.5 MB/s 
     |████████████████████████████████| 10.1 MB 23.3 MB/s 
     |████████████████████████████████| 49 kB 6.0 MB/s 
     |████████████████████████████████| 65 kB 3.7 MB/s 
     |████████████████████████████████| 97 kB 5.6 MB/s 
     |████████████████████████████████| 145 kB 36.8 MB/s 
     |████████████████████████████████| 53 kB 2.2 MB/s 
     |████████████████████████████████| 220 kB 59.3 MB/s 
     |████████████████████████████████| 229 kB 45.1 MB/s 
     |████████████████████████████████| 43 kB 2.1 MB/s 
     |████████████████████████████████| 38.1 MB 1.2 MB/s 
     |████████████████████████████████| 243 kB 58.6 MB/s 
     |████████████████████████

In [1]:
import numpy as np

In [5]:
x=1

In [13]:
a=np.array([[1,2],
           [3,4]])
a

array([[1, 2],
       [3, 4]])

In [11]:
a.shape

(3, 2)

In [16]:
b=np.array([[3,4],
            [4,5]])

In [18]:
a@b

array([[11, 14],
       [25, 32]])

In [20]:
c=np.dot(a,b)
c

array([[11, 14],
       [25, 32]])

In [21]:
a*b

array([[ 3,  8],
       [12, 20]])

In [23]:
np.multiply(a,b)

array([[ 3,  8],
       [12, 20]])

In [25]:
a

array([[1, 2],
       [3, 4]])

In [24]:
c=np.prod(a)
c

24

In [26]:
o=np.zeros((3,2))
o

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
one=np.ones((4,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.sum(a)

10

In [29]:
a

array([[1, 2],
       [3, 4]])

In [30]:
np.cumsum(a,axis=1)

array([[1, 3],
       [3, 7]])

In [31]:
np.cumsum(a,axis=0)

array([[1, 2],
       [4, 6]])

In [33]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[3 4]
 [4 5]]


In [32]:
np.subtract(a,b)

array([[-2, -2],
       [-1, -1]])

In [34]:
np.divide(a,3)

array([[0.33333333, 0.66666667],
       [1.        , 1.33333333]])

In [35]:
np.floor_divide(a,3)

array([[0, 0],
       [1, 1]])

In [36]:
x=[]
for i in range(1000):
  x.append(i)

In [42]:
x.shape

AttributeError: ignored

In [48]:
xx=np.array([x])
xx.shape

(1, 1000)

In [49]:
xx1=xx.reshape(-1,1)
xx1.shape

(1000, 1)

In [52]:
xx2=xx.reshape(500,2)
xx2.shape

(500, 2)

In [54]:
a=np.linspace(0,1000,10)
a

array([   0.        ,  111.11111111,  222.22222222,  333.33333333,
        444.44444444,  555.55555556,  666.66666667,  777.77777778,
        888.88888889, 1000.        ])

In [57]:
b=np.arange(0,100,5)
b

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [60]:
a=np.random.uniform(0,1,(3,3))
a

array([[0.90071303, 0.31901313, 0.61170461],
       [0.27609471, 0.92896651, 0.6645554 ],
       [0.08357878, 0.86858712, 0.09052785]])

In [62]:
b=np.random.standard_normal((4,2))
b

array([[ 0.04643845, -1.2328958 ],
       [-1.13033583, -0.7912452 ],
       [ 0.76614341,  0.4741813 ],
       [ 0.06491805, -0.0223288 ]])

In [63]:
np.size(b)

8

In [64]:
np.shape(b)#b.shape

(4, 2)

In [65]:
a=np.array([[1,2,3,2,4,1,5,7]])
b=np.array([[4,6,3,2,6,3,1,2]])

In [66]:
np.unique(a)

array([1, 2, 3, 4, 5, 7])

In [67]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
np.intersect1d(a,b)

array([1, 2, 3, 4])

In [70]:
np.var(a)

3.859375

In [71]:
np.std(a)

1.964529205687714

In [72]:
np.cov(a,b)

array([[ 4.41071429, -1.33928571],
       [-1.33928571,  3.41071429]])

In [73]:
np.median(a)

2.5

In [74]:
np.mean(a)

3.125

In [83]:
x=np.array([1,2,3,4,5,6,7,8])
y=np.array([8,7,8,6,4,3,2,1])

In [84]:
from scipy.stats import pearsonr 
p_coeef,p_value=pearsonr(x,y)

In [85]:
p_coeef,p_value

(-0.965520638020166, 9.984326049385874e-05)